#!/bin/bash

# Change encryption password for a LUKS drive

encrypted_drives=$(blkid -t TYPE=crypto_LUKS -o device 2>/dev/null)

if [[ -z $encrypted_drives ]]; then
  echo "No encrypted drives found."
  exit 1
fi

if (( $(echo "$encrypted_drives" | wc -l) == 1 )); then
  drive_to_change="$encrypted_drives"
else
  drive_to_change=$(echo "$encrypted_drives" | gum choose --header "Select drive")
  [[ -z $drive_to_change ]] && exit 0
fi

echo "Changing full-disk encryption password for $drive_to_change"
sudo cryptsetup luksChangeKey --pbkdf argon2id --iter-time 2000 "$drive_to_change"
