#!/bin/bash

# Fuzzy package removal picker using fzf

pkg_names=$(paru -Qqe | fzf \
    --with-shell='bash -c' \
    --multi \
    --preview 'paru -Qi {1}' \
    --preview-label='alt-p: toggle preview, alt-j/k: scroll, tab: multi-select' \
    --preview-label-pos='bottom' \
    --preview-window 'down:65%:wrap' \
    --bind 'alt-p:toggle-preview' \
    --bind 'alt-d:preview-half-page-down,alt-u:preview-half-page-up' \
    --bind 'alt-k:preview-up,alt-j:preview-down' \
    --color 'pointer:red,marker:red')

if [[ -n $pkg_names ]]; then
    echo "$pkg_names" | tr '\n' ' ' | xargs paru -Rns
fi
