source = ~/.config/hypr/startup.conf
source = ~/.config/theme/current/hyprland.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybinds.conf
