# Ristretto
accent = "#f38d70"
cursor = "#c3b7b8"
foreground = "#e6d9db"
background = "#2c2525"
selection_foreground = "#e6d9db"
selection_background = "#403e41"

color0 = "#72696a"
color1 = "#fd6883"
color2 = "#adda78"
color3 = "#f9cc6c"
color4 = "#f38d70"
color5 = "#a8a9eb"
color6 = "#85dacc"
color7 = "#e6d9db"
color8 = "#948a8b"
color9 = "#ff8297"
color10 = "#c8e292"
color11 = "#fcd675"
color12 = "#f8a788"
color13 = "#bebffd"
color14 = "#9bf1e1"
color15 = "#f1e5e7"

mauve = "#a8a9eb"
red = "#fd6883"
maroon = "#ff8297"
peach = "#f38d70"
yellow = "#f9cc6c"
green = "#adda78"
teal = "#85dacc"
sky = "#85dacc"
sapphire = "#f38d70"
blue = "#f38d70"
lavender = "#bebffd"
text = "#e6d9db"
subtext1 = "#f1e5e7"
subtext0 = "#c3b7b8"
overlay2 = "#948a8b"
overlay1 = "#807677"
overlay0 = "#72696a"
surface2 = "#504b4c"
surface1 = "#403e41"
surface0 = "#352f30"
base = "#2c2525"
mantle = "#241e1e"
crust = "#1c1717"
flamingo = "#fd6883"
pink = "#a8a9eb"
rosewater = "#f1e5e7"

nvim_colorscheme = "catppuccin"
nvim_plugin = "catppuccin/nvim"
cursor_theme = "Bibata-Modern-Classic"
