# Kanagawa
accent = "#7e9cd8"
cursor = "#c8c093"
foreground = "#dcd7ba"
background = "#1f1f28"
selection_foreground = "#c8c093"
selection_background = "#2d4f67"

color0 = "#090618"
color1 = "#c34043"
color2 = "#76946a"
color3 = "#c0a36e"
color4 = "#7e9cd8"
color5 = "#957fb8"
color6 = "#6a9589"
color7 = "#c8c093"
color8 = "#727169"
color9 = "#e82424"
color10 = "#98bb6c"
color11 = "#e6c384"
color12 = "#7fb4ca"
color13 = "#938aa9"
color14 = "#7aa89f"
color15 = "#dcd7ba"

mauve = "#957fb8"
red = "#c34043"
maroon = "#e82424"
peach = "#ffa066"
yellow = "#c0a36e"
green = "#76946a"
teal = "#6a9589"
sky = "#7fb4ca"
sapphire = "#7e9cd8"
blue = "#7e9cd8"
lavender = "#938aa9"
text = "#dcd7ba"
subtext1 = "#c8c093"
subtext0 = "#a6a69c"
overlay2 = "#727169"
overlay1 = "#54546d"
overlay0 = "#363646"
surface2 = "#54546d"
surface1 = "#363646"
surface0 = "#2a2a37"
base = "#1f1f28"
mantle = "#1a1a22"
crust = "#16161d"
flamingo = "#e82424"
pink = "#d27e99"
rosewater = "#dcd7ba"

nvim_colorscheme = "kanagawa"
nvim_plugin = "rebelot/kanagawa.nvim"
cursor_theme = "Bibata-Modern-Classic"
