source = ~/.config/theme/current/hyprland.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/startup.conf

misc {
    force_default_wallpaper = 0
    allow_session_lock_restore = true
}

binds {
    workspace_back_and_forth = true
}
