# ── Window rules ─────────────────────────────────────────────────

xwayland {
    force_zero_scaling = true
}

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
    workspace = special:hidden silent
}

windowrule = suppress_event maximize, match:class .*
windowrule = idle_inhibit always, match:fullscreen 1

windowrule = float on, match:class wdisplays
windowrule = size 800 600, match:class wdisplays
windowrule = center on, match:class wdisplays

windowrule  {
    name = floating-tui
    match:class = floating-tui
    float = on
    center = on
    size = 875 600
}

windowrule  {
    name = floating-tui-large
    match:class = floating-tui-large
    float = on
    center = on
    size = 1200 700
}

# ── Layer rules ──────────────────────────────────────────────────

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.3, match:namespace rofi

layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.3, match:namespace swaync-control-center
layerrule = ignore_alpha 0.3, match:namespace swaync-notification-window

layerrule = blur on, match:namespace logout_dialog
layerrule = ignore_alpha 0.3, match:namespace logout_dialog
