# Nord
accent = "#81a1c1"
cursor = "#d8dee9"
foreground = "#d8dee9"
background = "#2e3440"
selection_foreground = "#d8dee9"
selection_background = "#4c566a"

color0 = "#3b4252"
color1 = "#bf616a"
color2 = "#a3be8c"
color3 = "#ebcb8b"
color4 = "#81a1c1"
color5 = "#b48ead"
color6 = "#88c0d0"
color7 = "#e5e9f0"
color8 = "#4c566a"
color9 = "#bf616a"
color10 = "#a3be8c"
color11 = "#ebcb8b"
color12 = "#81a1c1"
color13 = "#b48ead"
color14 = "#8fbcbb"
color15 = "#eceff4"

mauve = "#b48ead"
red = "#bf616a"
maroon = "#bf616a"
peach = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
teal = "#8fbcbb"
sky = "#88c0d0"
sapphire = "#81a1c1"
blue = "#81a1c1"
lavender = "#b48ead"
text = "#d8dee9"
subtext1 = "#e5e9f0"
subtext0 = "#d8dee9"
overlay2 = "#4c566a"
overlay1 = "#434c5e"
overlay0 = "#3b4252"
surface2 = "#4c566a"
surface1 = "#434c5e"
surface0 = "#3b4252"
base = "#2e3440"
mantle = "#2e3440"
crust = "#242933"
flamingo = "#bf616a"
pink = "#b48ead"
rosewater = "#d8dee9"

nvim_colorscheme = "nord"
nvim_plugin = "shaunsingh/nord.nvim"
cursor_theme = "Bibata-Modern-Classic"
