# Font
font_family JetBrainsMono Nerd Font
font_size        11

# Shell
shell            fish
shell_integration no-sudo
confirm_os_window_close 0

# Window
window_padding_width 4
background_opacity   0.7

# Cursor
cursor_shape          beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.5

# URL handling
url_style        single
open_url_with    xdg-open
detect_urls      yes

# Colors (managed by theme-set)
include ~/.config/theme/current/kitty.conf
