exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 28
exec-once = regreet; hyprctl dispatch exit

monitor = , preferred, auto, auto
monitor = eDP-1, preferred, auto, 1.6

env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = XCURSOR_SIZE,28
env = HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_SIZE,28

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    disable_hyprland_guiutils_check = true
}
