# Everforest
accent = "#7fbbb3"
cursor = "#d3c6aa"
foreground = "#d3c6aa"
background = "#2d353b"
selection_foreground = "#2d353b"
selection_background = "#d3c6aa"

color0 = "#475258"
color1 = "#e67e80"
color2 = "#a7c080"
color3 = "#dbbc7f"
color4 = "#7fbbb3"
color5 = "#d699b6"
color6 = "#83c092"
color7 = "#d3c6aa"
color8 = "#475258"
color9 = "#e67e80"
color10 = "#a7c080"
color11 = "#dbbc7f"
color12 = "#7fbbb3"
color13 = "#d699b6"
color14 = "#83c092"
color15 = "#d3c6aa"

mauve = "#d699b6"
red = "#e67e80"
maroon = "#e67e80"
peach = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
teal = "#83c092"
sky = "#7fbbb3"
sapphire = "#7fbbb3"
blue = "#7fbbb3"
lavender = "#d699b6"
text = "#d3c6aa"
subtext1 = "#d3c6aa"
subtext0 = "#9da9a0"
overlay2 = "#859289"
overlay1 = "#6e7b72"
overlay0 = "#5d6b66"
surface2 = "#4f585e"
surface1 = "#475258"
surface0 = "#3d484d"
base = "#2d353b"
mantle = "#272e33"
crust = "#232a2e"
flamingo = "#e67e80"
pink = "#d699b6"
rosewater = "#d3c6aa"

nvim_colorscheme = "everforest"
nvim_plugin = "sainnhe/everforest"
cursor_theme = "Bibata-Modern-Classic"
