# Matte Black
accent = "#e68e0d"
cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

color0 = "#333333"
color1 = "#D35F5F"
color2 = "#FFC107"
color3 = "#b91c1c"
color4 = "#e68e0d"
color5 = "#D35F5F"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"

mauve = "#e68e0d"
red = "#D35F5F"
maroon = "#B91C1C"
peach = "#f59e0b"
yellow = "#FFC107"
green = "#FFC107"
teal = "#bebebe"
sky = "#eaeaea"
sapphire = "#e68e0d"
blue = "#e68e0d"
lavender = "#D35F5F"
text = "#bebebe"
subtext1 = "#eaeaea"
subtext0 = "#8a8a8d"
overlay2 = "#8a8a8d"
overlay1 = "#666666"
overlay0 = "#4d4d4d"
surface2 = "#444444"
surface1 = "#333333"
surface0 = "#262626"
base = "#121212"
mantle = "#0d0d0d"
crust = "#080808"
flamingo = "#D35F5F"
pink = "#D35F5F"
rosewater = "#eaeaea"

nvim_colorscheme = "catppuccin"
nvim_plugin = "catppuccin/nvim"
cursor_theme = "Bibata-Modern-Classic"
