# Miasma
accent = "#78824b"
cursor = "#c7c7c7"
foreground = "#c2c2b0"
background = "#222222"
selection_foreground = "#c2c2b0"
selection_background = "#78824b"

color0 = "#000000"
color1 = "#685742"
color2 = "#5f875f"
color3 = "#b36d43"
color4 = "#78824b"
color5 = "#bb7744"
color6 = "#c9a554"
color7 = "#d7c483"
color8 = "#666666"
color9 = "#685742"
color10 = "#5f875f"
color11 = "#b36d43"
color12 = "#78824b"
color13 = "#bb7744"
color14 = "#c9a554"
color15 = "#d7c483"

mauve = "#bb7744"
red = "#685742"
maroon = "#685742"
peach = "#b36d43"
yellow = "#c9a554"
green = "#5f875f"
teal = "#78824b"
sky = "#c9a554"
sapphire = "#78824b"
blue = "#78824b"
lavender = "#bb7744"
text = "#c2c2b0"
subtext1 = "#d7c483"
subtext0 = "#a0a090"
overlay2 = "#666666"
overlay1 = "#555555"
overlay0 = "#444444"
surface2 = "#3a3a3a"
surface1 = "#333333"
surface0 = "#2a2a2a"
base = "#222222"
mantle = "#1a1a1a"
crust = "#111111"
flamingo = "#b36d43"
pink = "#bb7744"
rosewater = "#d7c483"

nvim_colorscheme = "miasma"
nvim_plugin = "xero/miasma.nvim"
cursor_theme = "Bibata-Modern-Classic"
