# Osaka Jade
accent = "#509475"
cursor = "#D7C995"
foreground = "#C1C497"
background = "#111c18"
selection_foreground = "#111C18"
selection_background = "#C1C497"

color0 = "#23372B"
color1 = "#FF5345"
color2 = "#549e6a"
color3 = "#459451"
color4 = "#509475"
color5 = "#D2689C"
color6 = "#2DD5B7"
color7 = "#F6F5DD"
color8 = "#53685B"
color9 = "#db9f9c"
color10 = "#63b07a"
color11 = "#E5C736"
color12 = "#ACD4CF"
color13 = "#75bbb3"
color14 = "#8CD3CB"
color15 = "#9eebb3"

mauve = "#D2689C"
red = "#FF5345"
maroon = "#db9f9c"
peach = "#E5C736"
yellow = "#459451"
green = "#549e6a"
teal = "#2DD5B7"
sky = "#ACD4CF"
sapphire = "#509475"
blue = "#509475"
lavender = "#75bbb3"
text = "#C1C497"
subtext1 = "#F6F5DD"
subtext0 = "#9eebb3"
overlay2 = "#53685B"
overlay1 = "#405048"
overlay0 = "#334038"
surface2 = "#2e3d34"
surface1 = "#23372B"
surface0 = "#1a2b22"
base = "#111c18"
mantle = "#0d1613"
crust = "#09100e"
flamingo = "#db9f9c"
pink = "#D2689C"
rosewater = "#D7C995"

nvim_colorscheme = "catppuccin"
nvim_plugin = "catppuccin/nvim"
cursor_theme = "Bibata-Modern-Classic"
