# Vantablack
accent = "#8d8d8d"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#0d0d0d"
selection_foreground = "#0d0d0d"
selection_background = "#ffffff"

color0 = "#0d0d0d"
color1 = "#a4a4a4"
color2 = "#b6b6b6"
color3 = "#cecece"
color4 = "#8d8d8d"
color5 = "#9b9b9b"
color6 = "#b0b0b0"
color7 = "#ececec"
color8 = "#fdfdfd"
color9 = "#a4a4a4"
color10 = "#b6b6b6"
color11 = "#cecece"
color12 = "#8d8d8d"
color13 = "#9b9b9b"
color14 = "#b0b0b0"
color15 = "#ffffff"

mauve = "#9b9b9b"
red = "#a4a4a4"
maroon = "#a4a4a4"
peach = "#b0b0b0"
yellow = "#cecece"
green = "#b6b6b6"
teal = "#b0b0b0"
sky = "#ececec"
sapphire = "#8d8d8d"
blue = "#8d8d8d"
lavender = "#9b9b9b"
text = "#ffffff"
subtext1 = "#ececec"
subtext0 = "#cecece"
overlay2 = "#b0b0b0"
overlay1 = "#9b9b9b"
overlay0 = "#8d8d8d"
surface2 = "#3a3a3a"
surface1 = "#2a2a2a"
surface0 = "#1a1a1a"
base = "#0d0d0d"
mantle = "#080808"
crust = "#040404"
flamingo = "#a4a4a4"
pink = "#9b9b9b"
rosewater = "#ececec"

nvim_colorscheme = "catppuccin"
nvim_plugin = "catppuccin/nvim"
cursor_theme = "Bibata-Modern-Classic"
