# Autostart Applications

# Wayland env for portals, screen sharing, tray apps
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland

# Wallpaper
exec-once = hyprpaper

# Status bar
exec-once = waybar -c ~/.config/waybar/config-hyprland.jsonc -s ~/.config/waybar/style-hyprland.css

# Notifications
exec-once = swaync

# Clipboard
exec-once = wl-paste --watch cliphist store

# Network manager applet
exec-once = nm-applet --indicator

# Unlock Bitwarden vault
exec-once = rbw unlock

# Idle management
exec-once = hypridle

# Cursor theme
exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 24
