# Flexoki Light
accent = "#205EA6"
cursor = "#100F0F"
foreground = "#100F0F"
background = "#FFFCF0"
selection_foreground = "#100F0F"
selection_background = "#CECDC3"

color0 = "#100F0F"
color1 = "#D14D41"
color2 = "#879A39"
color3 = "#D0A215"
color4 = "#205EA6"
color5 = "#CE5D97"
color6 = "#3AA99F"
color7 = "#FFFCF0"
color8 = "#100F0F"
color9 = "#D14D41"
color10 = "#879A39"
color11 = "#D0A215"
color12 = "#4385BE"
color13 = "#CE5D97"
color14 = "#3AA99F"
color15 = "#FFFCF0"

mauve = "#CE5D97"
red = "#D14D41"
maroon = "#D14D41"
peach = "#DA702C"
yellow = "#D0A215"
green = "#879A39"
teal = "#3AA99F"
sky = "#4385BE"
sapphire = "#205EA6"
blue = "#205EA6"
lavender = "#CE5D97"
text = "#100F0F"
subtext1 = "#1C1B1A"
subtext0 = "#343331"
overlay2 = "#575653"
overlay1 = "#6F6E69"
overlay0 = "#878580"
surface2 = "#B7B5AC"
surface1 = "#CECDC3"
surface0 = "#E6E4D9"
base = "#FFFCF0"
mantle = "#F2F0E5"
crust = "#E6E4D9"
flamingo = "#D14D41"
pink = "#CE5D97"
rosewater = "#CECDC3"

nvim_colorscheme = "catppuccin-latte"
nvim_plugin = "catppuccin/nvim"
cursor_theme = "Bibata-Modern-Classic"
