# Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",foot*:Tc:RGB,xterm-256color:Tc:RGB,xterm-kitty:Tc:RGB"
set -s extended-keys on
set -g allow-passthrough on
set-option -g default-shell "/usr/bin/zsh"

# Prefix
set -g prefix C-a

# General
set-window-option -g mode-keys vi
set -g set-titles on
set -g set-titles-string "#{?#{m:ephemeral-*,#{session_name}},#{pane_current_command},#{session_name}: #{pane_current_command}}"
set -g mouse on

# Status bar
set -g status-interval 1
set -g status-justify centre
set-option -g status-position bottom
set-window-option -g window-status-format " #I:#W "
set-window-option -g window-status-current-format " #I:#W "
bind -n M-h previous-window
bind -n M-l next-window

# Activity
setw -g monitor-activity on
set -g visual-activity on

source-file ~/.config/theme/current/tmux.conf
set -g status-left-length 70
set -g status-left "#[fg=default] #h :: #(ip addr show $(route | grep '^default' | grep -o '[^ ]*$') | awk '/inet /{print $2}' | awk -F/ '{print $1}' ) :: #S:#I:#P"
set -g status-right-length 60
set -g status-right "#[fg=default]#(tmux-mem-cpu-load) "

# Key bindings
bind B break-pane
bind C copy-mode
bind S setw synchronize-panes \; display "Toggling pane synchronization state"
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind ^D detach
bind * list-clients
bind / command-prompt "split-window -h 'exec man %%'"

# Windows
bind '"' choose-window
bind A command-prompt "rename-window %%"
bind space next-layout

# Panes
bind z split-window -h -c '#{pane_current_path}'
bind a split-window -v -c '#{pane_current_path}'
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind Z resize-pane -Z
bind o select-pane -t :.+
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind x kill-pane
bind X kill-window

# Server
bind ^K confirm-before "kill-server"
bind ^L refresh-client

# Clipboard (Wayland)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Session picker
bind-key "." run-shell "sesh-picker"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
run ~/.tmux/plugins/tpm/tpm
