# Ethereal
accent = "#7d82d9"
cursor = "#ffcead"
foreground = "#ffcead"
background = "#060B1E"
selection_foreground = "#060B1E"
selection_background = "#ffcead"

color0 = "#060B1E"
color1 = "#ED5B5A"
color2 = "#92a593"
color3 = "#E9BB4F"
color4 = "#7d82d9"
color5 = "#c89dc1"
color6 = "#a3bfd1"
color7 = "#F99957"
color8 = "#6d7db6"
color9 = "#faaaa9"
color10 = "#c4cfc4"
color11 = "#f7dc9c"
color12 = "#c2c4f0"
color13 = "#ead7e7"
color14 = "#dfeaf0"
color15 = "#ffcead"

mauve = "#c89dc1"
red = "#ED5B5A"
maroon = "#faaaa9"
peach = "#F99957"
yellow = "#E9BB4F"
green = "#92a593"
teal = "#a3bfd1"
sky = "#a3bfd1"
sapphire = "#7d82d9"
blue = "#7d82d9"
lavender = "#c2c4f0"
text = "#ffcead"
subtext1 = "#dfeaf0"
subtext0 = "#c2c4f0"
overlay2 = "#6d7db6"
overlay1 = "#5a6899"
overlay0 = "#485380"
surface2 = "#3a4266"
surface1 = "#2a3050"
surface0 = "#1a2040"
base = "#060B1E"
mantle = "#050918"
crust = "#040712"
flamingo = "#faaaa9"
pink = "#ead7e7"
rosewater = "#ffcead"

nvim_colorscheme = "catppuccin"
nvim_plugin = "catppuccin/nvim"
cursor_theme = "Bibata-Modern-Classic"
