general {
    border_size = 3

    col.active_border = $mauve
    col.inactive_border = $subtext0

    resize_on_border = true

    gaps_in = 4
    gaps_out = 8

    layout = master

    allow_tearing = false
}

decoration {
    rounding = 5

    blur {
        enabled = true
        size = 6
        passes = 3
        xray = false
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    dim_inactive = true
    dim_strength = 0.20
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     3.03,  quick
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = workspaces,    1,     1.94,  almostLinear, fade
    animation = workspacesIn,  1,     1.21,  almostLinear, fade
    animation = workspacesOut, 1,     1.94,  almostLinear, fade
    animation = zoomFactor,    1,     7,     quick
}

master {
    new_status = slave
    orientation = left
    mfact = 0.55
}

group {
    col.border_active = $mauve
    col.border_inactive = $surface1

    groupbar {
        font_family = monospace
        font_size = 14
        height = 26
        text_color = $text
        col.active = $mauve
        col.inactive = $surface0
    }
}
