general {
  lock_cmd = pidof hyprlock || hyprlock --immediate-render --no-fade-in -q
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
  inhibit_sleep = 3
}

listener {
  timeout = 300
  on-timeout = brightnessctl -s set 10
  on-resume = brightnessctl -r
}

listener {
  timeout = 330
  on-timeout = loginctl lock-session
}

listener {
  timeout = 350
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# listener {
#   timeout = 1800
#   on-timeout = systemctl suspend
# }
