input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    repeat_delay = 300
    repeat_rate = 40

    follow_mouse = 1
    touchpad {
        natural_scroll = true
        clickfinger_behavior = true
        tap-to-click = false
    }

    emulate_discrete_scroll = false

    sensitivity = 0
}

cursor {
    inactive_timeout = 3
    warp_on_change_workspace = true
}
