autotype_command = 'wtype -- %VALUE%'
autotype_delay = 500
autotype_support = true
clear_after = 5
clear_command = 'wl-copy --clear'
copy_command = "wl-copy --"

[Config]
hide_from_providerlist = false
icon = ''
min_score = 20
name_pretty = ''
