# Gruvbox
accent = "#7daea3"
cursor = "#bdae93"
foreground = "#d4be98"
background = "#282828"
selection_foreground = "#ebdbb2"
selection_background = "#d65d0e"

color0 = "#3c3836"
color1 = "#ea6962"
color2 = "#a9b665"
color3 = "#d8a657"
color4 = "#7daea3"
color5 = "#d3869b"
color6 = "#89b482"
color7 = "#d4be98"
color8 = "#3c3836"
color9 = "#ea6962"
color10 = "#a9b665"
color11 = "#d8a657"
color12 = "#7daea3"
color13 = "#d3869b"
color14 = "#89b482"
color15 = "#d4be98"

mauve = "#d3869b"
red = "#ea6962"
maroon = "#ea6962"
peach = "#d65d0e"
yellow = "#d8a657"
green = "#a9b665"
teal = "#89b482"
sky = "#89b482"
sapphire = "#7daea3"
blue = "#7daea3"
lavender = "#d3869b"
text = "#d4be98"
subtext1 = "#bdae93"
subtext0 = "#a89984"
overlay2 = "#928374"
overlay1 = "#7c6f64"
overlay0 = "#665c54"
surface2 = "#504945"
surface1 = "#3c3836"
surface0 = "#32302f"
base = "#282828"
mantle = "#1d2021"
crust = "#1d2021"
flamingo = "#ea6962"
pink = "#d3869b"
rosewater = "#d4be98"

nvim_colorscheme = "gruvbox-material"
nvim_plugin = "sainnhe/gruvbox-material"
cursor_theme = "Bibata-Modern-Classic"
