#!/bin/bash

# Change encryption password for a LUKS drive

encrypted_drives=""
while read -r dev _ size parent; do
  model=$(lsblk -dnpo MODEL "$parent" 2>/dev/null | sed 's/\\x20/ /g')
  encrypted_drives+="$dev  ${size}  ${model:-(unknown)}"$'\n'
done < <(lsblk -nrpo NAME,FSTYPE,SIZE,PKNAME | awk '$2 == "crypto_LUKS"')
encrypted_drives=${encrypted_drives%$'\n'}

if [[ -z $encrypted_drives ]]; then
  echo "No encrypted drives found."
  exit 1
fi

if (( $(echo "$encrypted_drives" | wc -l) == 1 )); then
  drive_to_change=$(echo "$encrypted_drives" | awk '{print $1}')
else
  drive_to_change=$(echo "$encrypted_drives" | fzf --header "Select drive" | awk '{print $1}')
  [[ -z $drive_to_change ]] && exit 0
fi

echo "Changing full-disk encryption password for $drive_to_change"
sudo cryptsetup luksChangeKey --pbkdf argon2id --iter-time 2000 "$drive_to_change"
