# Rose Pine
accent = "#56949f"
cursor = "#cecacd"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#575279"
selection_background = "#dfdad9"

color0 = "#f2e9e1"
color1 = "#b4637a"
color2 = "#286983"
color3 = "#ea9d34"
color4 = "#56949f"
color5 = "#907aa9"
color6 = "#d7827e"
color7 = "#575279"
color8 = "#9893a5"
color9 = "#b4637a"
color10 = "#286983"
color11 = "#ea9d34"
color12 = "#56949f"
color13 = "#907aa9"
color14 = "#d7827e"
color15 = "#575279"

mauve = "#907aa9"
red = "#b4637a"
maroon = "#b4637a"
peach = "#d7827e"
yellow = "#ea9d34"
green = "#286983"
teal = "#56949f"
sky = "#56949f"
sapphire = "#286983"
blue = "#56949f"
lavender = "#907aa9"
text = "#575279"
subtext1 = "#6e6a86"
subtext0 = "#9893a5"
overlay2 = "#9893a5"
overlay1 = "#b4b0be"
overlay0 = "#cecacd"
surface2 = "#dfdad9"
surface1 = "#f2e9e1"
surface0 = "#fffaf3"
base = "#faf4ed"
mantle = "#f2e9de"
crust = "#e4ddd6"
flamingo = "#d7827e"
pink = "#907aa9"
rosewater = "#cecacd"

nvim_colorscheme = "rose-pine"
nvim_plugin = "rose-pine/neovim"
cursor_theme = "Bibata-Modern-Classic"
